import { Classroom, Question } from '@/types';
import { CUTE_AVATARS } from './constants';

export const INITIAL_CLASSROOMS: Classroom[] = [
  {
    id: 'class-3a',
    name: 'Lớp 3A - Vui Vẻ',
    grade: 3,
    schoolYear: '2024 - 2025',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    students: [
      { id: 'st-1', stt: 1, fullName: 'Nguyễn Gia Bảo', gender: 'male', dob: '2016-03-15', stars: 5, avatar: '🦁', note: 'Hăng hái phát biểu' },
      { id: 'st-2', stt: 2, fullName: 'Trần Thảo Linh', gender: 'female', dob: '2016-07-22', stars: 7, avatar: '🐰', note: 'Chăm chỉ, hát hay' },
      { id: 'st-3', stt: 3, fullName: 'Lê Minh Khôi', gender: 'male', dob: '2016-11-05', stars: 4, avatar: '🦊', note: 'Tư duy toán tốt' },
      { id: 'st-4', stt: 4, fullName: 'Phạm Ngọc Ánh', gender: 'female', dob: '2016-02-18', stars: 6, avatar: '🐱', note: 'Viết chữ rất đẹp' },
      { id: 'st-5', stt: 5, fullName: 'Vũ Đức Nam', gender: 'male', dob: '2016-09-30', stars: 3, avatar: '🐼', note: 'Hài hước, nhanh nhẹn' },
      { id: 'st-6', stt: 6, fullName: 'Đỗ Hà My', gender: 'female', dob: '2016-05-12', stars: 8, avatar: '🦄', note: 'Lớp phó học tập' },
      { id: 'st-7', stt: 7, fullName: 'Hoàng Quốc Tuấn', gender: 'male', dob: '2016-08-25', stars: 4, avatar: '🐶', note: 'Thích vẽ tranh' },
      { id: 'st-8', stt: 8, fullName: 'Bùi Phương Uyên', gender: 'female', dob: '2016-01-10', stars: 6, avatar: '🐥', note: 'Đọc thơ diễn cảm' },
      { id: 'st-9', stt: 9, fullName: 'Ngô Hải Đăng', gender: 'male', dob: '2016-10-14', stars: 5, avatar: '🚀', note: 'Tò mò khoa học' },
      { id: 'st-10', stt: 10, fullName: 'Đinh Mai Trang', gender: 'female', dob: '2016-04-03', stars: 9, avatar: '🌟', note: 'Hăng hái giúp bạn' },
      { id: 'st-11', stt: 11, fullName: 'Lý Quốc An', gender: 'male', dob: '2016-12-19', stars: 4, avatar: '🐨', note: 'Điềm tĩnh, quan sát' },
      { id: 'st-12', stt: 12, fullName: 'Dương Khánh Linh', gender: 'female', dob: '2016-06-28', stars: 6, avatar: '🦋', note: 'Vui vẻ, hòa đồng' },
      { id: 'st-13', stt: 13, fullName: 'Phan Trọng Khang', gender: 'male', dob: '2016-07-07', stars: 5, avatar: '🦖', note: 'Thích thể thao' },
      { id: 'st-14', stt: 14, fullName: 'Trịnh Bảo Ngọc', gender: 'female', dob: '2016-09-11', stars: 7, avatar: '🐬', note: 'Tiếng Anh tốt' },
      { id: 'st-15', stt: 15, fullName: 'Lâm Tuấn Kiệt', gender: 'male', dob: '2016-03-24', stars: 4, avatar: '🐯', note: 'Chăm chú lắng nghe' },
    ],
  },
  {
    id: 'class-2b',
    name: 'Lớp 2B - Sao Sáng',
    grade: 2,
    schoolYear: '2024 - 2025',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    students: [
      { id: 'st-201', stt: 1, fullName: 'Nguyễn An Nhiên', gender: 'female', stars: 3, avatar: '🌸' },
      { id: 'st-202', stt: 2, fullName: 'Đặng Minh Đăng', gender: 'male', stars: 4, avatar: '🦁' },
      { id: 'st-203', stt: 3, fullName: 'Vũ Thảo Vy', gender: 'female', stars: 5, avatar: '🐰' },
      { id: 'st-204', stt: 4, fullName: 'Trần Tuấn Khang', gender: 'male', stars: 2, avatar: '🚀' },
    ],
  },
];

export const INITIAL_QUESTIONS: Question[] = [
  // Toán học
  {
    id: 'q-m1',
    subjectId: 'toan',
    grade: 3,
    topic: 'Bảng nhân và chia',
    lesson: 'Bảng nhân 7',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Kết quả của phép tính: 7 × 8 = ?',
    options: ['54', '56', '58', '63'],
    correctAnswer: '56',
    explanation: 'Theo bảng nhân 7: 7 × 8 = 56 nhé các em!',
  },
  {
    id: 'q-m2',
    subjectId: 'toan',
    grade: 3,
    topic: 'Hình học phẳng',
    lesson: 'Hình chữ nhật',
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Một hình chữ nhật có chiều dài 8cm, chiều rộng 5cm. Chu vi của hình chữ nhật đó là bao nhiêu cm?',
    options: ['13 cm', '26 cm', '40 cm', '20 cm'],
    correctAnswer: '26 cm',
    explanation: 'Chu vi hình chữ nhật = (Dài + Rộng) × 2 = (8 + 5) × 2 = 13 × 2 = 26 cm.',
  },
  {
    id: 'q-m3',
    subjectId: 'toan',
    grade: 3,
    topic: 'Giải toán có lời văn',
    lesson: 'Gấp một số lên nhiều lần',
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'Bình có 6 viên bi. Số bi của Nam gấp 4 lần số bi của Bình. Hỏi cả hai bạn có tất cả bao nhiêu viên bi?',
    options: ['24 viên bi', '30 viên bi', '10 viên bi', '28 viên bi'],
    correctAnswer: '30 viên bi',
    explanation: 'Số bi của Nam: 6 × 4 = 24 viên. Cả hai bạn có: 6 + 24 = 30 viên bi!',
  },
  {
    id: 'q-m4',
    subjectId: 'toan',
    grade: 2,
    topic: 'Phép cộng có nhớ',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Tính nhanh: 38 + 25 = ?',
    options: ['63', '53', '65', '73'],
    correctAnswer: '63',
    explanation: '8 + 5 = 13 viết 3 nhớ 1; 3 + 2 = 5 thêm 1 là 6. Kết quả là 63!',
  },
  {
    id: 'q-m5',
    subjectId: 'toan',
    grade: 1,
    topic: 'Số và chữ số',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Số liền sau của số 19 là số nào?',
    options: ['18', '20', '21', '29'],
    correctAnswer: '20',
    explanation: 'Số liền sau hơn số đã cho 1 đơn vị: 19 + 1 = 20!',
  },

  // Tiếng Việt
  {
    id: 'q-tv1',
    subjectId: 'tieng_viet',
    grade: 3,
    topic: 'Luyện từ và câu',
    lesson: 'Từ ngữ chỉ gộp những người trong gia đình',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Từ nào sau đây KHÔNG phải là từ chỉ gộp những người trong gia đình?',
    options: ['Ông bà', 'Cha mẹ', 'Thầy trò', 'Anh chị'],
    correctAnswer: 'Thầy trò',
    explanation: '"Thầy trò" là từ chỉ quan hệ trong trường lớp, không phải trong gia đình!',
  },
  {
    id: 'q-tv2',
    subjectId: 'tieng_viet',
    grade: 3,
    topic: 'Biện pháp tu từ',
    lesson: 'So sánh',
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Trong câu thơ: "Trăng tròn như cái mâm con / Ai treo uốn lượn trên vòm trời cao", hình ảnh "Trăng tròn" được so sánh với gì?',
    options: ['Vòm trời cao', 'Cái mâm con', 'Quả bóng', 'Đèn lồng'],
    correctAnswer: 'Cái mâm con',
    explanation: 'Từ so sánh là "như", vế so sánh là "cái mâm con".',
  },
  {
    id: 'q-tv3',
    subjectId: 'tieng_viet',
    grade: 2,
    topic: 'Chính tả',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Từ nào sau đây viết ĐÚNG chính tả?',
    options: ['Xắp xếp', 'Sắp xếp', 'Sắp sếp', 'Xắp sếp'],
    correctAnswer: 'Sắp xếp',
    explanation: '"Sắp xếp" là cách viết đúng chuẩn chính tả Tiếng Việt.',
  },
  {
    id: 'q-tv4',
    subjectId: 'tieng_viet',
    grade: 4,
    topic: 'Thành ngữ - Tục ngữ',
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Điền từ còn thiếu vào câu thành ngữ: "Uống nước nhớ ..."',
    options: ['cội', 'nguồn', 'sông', 'ơn'],
    correctAnswer: 'nguồn',
    explanation: 'Câu thành ngữ đầy đủ là: "Uống nước nhớ nguồn" - dạy chúng ta lòng biết ơn!',
  },

  // Tự nhiên và Xã hội
  {
    id: 'q-tnxh1',
    subjectId: 'tnxh',
    grade: 3,
    topic: 'Thực vật và động vật',
    lesson: 'Cơ quan hô hấp ở động vật',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Loài cá thở bằng cơ quan nào dưới nước?',
    options: ['Phổi', 'Mang', 'Da', 'Mũi'],
    correctAnswer: 'Mang',
    explanation: 'Cá hô hấp bằng mang bằng cách lấy khí oxy hòa tan trong nước!',
  },
  {
    id: 'q-tnxh2',
    subjectId: 'tnxh',
    grade: 2,
    topic: 'Cơ thể người và sức khỏe',
    lesson: 'Các giác quan',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Giác quan nào giúp chúng ta ngửi thấy mùi thơm của hoa quả?',
    options: ['Thị giác (Mắt)', 'Thính giác (Tai)', 'Khứu giác (Mũi)', 'Vị giác (Lưỡi)'],
    correctAnswer: 'Khứu giác (Mũi)',
    explanation: 'Khứu giác (mũi) là giác quan giúp chúng ta nhận biết mùi hương!',
  },
  {
    id: 'q-tnxh3',
    subjectId: 'tnxh',
    grade: 3,
    topic: 'Trái đất và bầu trời',
    lesson: 'Hiện tượng ngày và đêm',
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Trái đất quay quanh trục của nó theo hướng nào?',
    options: ['Từ Tây sang Đông', 'Từ Đông sang Tây', 'Từ Bắc xuống Nam', 'Từ Nam lên Bắc'],
    correctAnswer: 'Từ Tây sang Đông',
    explanation: 'Trái đất tự quay quanh trục theo chiều từ Tây sang Đông, làm cho Mặt Trời dường như mọc ở hướng Đông!',
  },

  // Tiếng Anh
  {
    id: 'q-en1',
    subjectId: 'tieng_anh',
    grade: 3,
    topic: 'Animals',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'What animal is known as "man\'s best friend" and barks "woof woof"?',
    options: ['Cat', 'Dog', 'Elephant', 'Bird'],
    correctAnswer: 'Dog',
    explanation: 'A dog barks and is often called man\'s best friend!',
  },
  {
    id: 'q-en2',
    subjectId: 'tieng_anh',
    grade: 2,
    topic: 'Colors',
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'What color do you get when you mix Yellow and Blue?',
    options: ['Purple', 'Orange', 'Green', 'Red'],
    correctAnswer: 'Green',
    explanation: 'Yellow + Blue = Green (Màu xanh lá cây)!',
  }
];
